name: Check Links
on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 1'
permissions:
  contents: read
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lycheeverse/lychee-action@v2
        with:
          args: --no-progress -- README.md curations/*.md
          fail: true
